name: Build

on:
  - push
  - pull_request

jobs:
  build:
    name: Build all platforms
    runs-on: ubuntu-latest
    container: 
      image: golang:1.23-bullseye
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up user
        run: |
          useradd -m -g users builduser
          chown -R builduser:users .
      - name: Build
        run: |
          su -c "make all" builduser
      - uses: actions/upload-artifact@v4
        with:
          name: Server binaries
          path: mauerspecht-server
      - uses: actions/upload-artifact@v4
        with:
          name: Client binaries
          path: mauerspecht-client*
